config/routes.rb
Rails.application.routes.draw do
  resources :nodes 
  root 'nodes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/node.rb
# app/models/node.rb

class Node < ApplicationRecord
  validates :title, presence: true
  belongs_to :parent, class_name: "Node", optional: true
  has_many :children, class_name: 'Node', foreign_key: 'parent_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  def index
    @nodes = Node.all
  end

  def show
    puts "Showing Node: #{@node.inspect}"
  end

  def new
    @node = Node.new
  end

  def create
    @node = Node.new(node_params)
    
    # Перевіряємо, чи передано значення для parent_id
    parent_id = params[:node][:parent_id]
    @node.parent_id = parent_id unless parent_id.blank?

    if @node.save
      redirect_to @node
    else
      render :edit
    end
  end
  

  def update
    if @node.update(node_params)
      
    else
      render :edit
    end
  rescue => e
    flash[:alert] = "Error updating node: #{e.message}"
    Rails.logger.error("Error updating node: #{e.message}")
  end

  def destroy
    if @node.destroy
      flash[:notice] = 'Node was successfully destroyed.'
    else
      flash[:alert] = 'Error destroying node.'
      Rails.logger.error("Error destroying node: #{node.errors.full_messages}")
    end
  
    respond_to do |format|
      format.html { redirect_to nodes_path }
      format.js   # це має відповідати за виклик destroy.js.erb
    end
  end
  
  private

  def set_node
    @node = Node.find(params[:id])
  end

  def node_params
    params.require(:node).permit(:title, :content, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
# app/helpers/nodes_helper.rb

module NodesHelper
    def arrow_indicator(node)
      node.children.any? ? content_tag(:span, '▶', class: 'arrow') : ''
    end
  end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>
 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/_child_node.html.erb
<li>
  <%= link_to node.title, node_path(node) %>
  <%= link_to 'Delete', node_path(node), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>

  <ul class="node-branches">
    <%= render partial: 'nodes/child_node', collection: node.children, as: :node %>
  </ul>
</li>

app/views/nodes/_form.html.erb
<%= form_with(model: @node, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.collection_select :parent_id, Node.all, :id, :title, { prompt: "Select parent node (optional)" } %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<!-- app/views/nodes/_node.html.erb -->

<li>
  <%= link_to node.title, node_path(node) %>

  <% if node.children.any? %>
    <ul>
      <%= render partial: 'node', collection: node.children, locals: { level: level + 1 } %>
    </ul>
  <% end %>
</li>

app/views/nodes/_root_node.html.erb
<li>
  <%= link_to node.title, node_path(node) %>
  

  <ul class="node-branches">
    <%= render partial: 'nodes/child_node', collection: node.children, as: :node %>
  </ul>
</li>

app/views/nodes/destroy.js.erb
location.reload();
console.log("Node destroyed successfully!");

app/views/nodes/edit.html.erb
<!-- app/views/nodes/edit.html.erb -->
<h1>Edit Node</h1>

<%= render 'form', node: @node %>
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<!-- app/views/nodes/index.html.erb -->

<div class="node-tree">
  <h1 class="node-center-title">Nodes List</h1>
  <div class="node-center">
    <%= link_to 'New Node', new_node_path, class: 'btn-new-node' %>
  </div>

  <ul class="node-branches">
    <% @nodes.where(parent_id: nil).each do |node| %>
      <%= render 'node', node: node, level: 0, on_index: true %>
    <% end %>
  </ul>
</div>

app/views/nodes/new.html.erb
<%= render 'form' %>

app/views/nodes/show.html.erb
<!-- app/views/nodes/show.html.erb -->

<p>
  <strong>Title:</strong>
  <%= @node.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @node.content %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>
<%= link_to 'Delete', @node, method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>